services:
    _defaults:
        autoconfigure: true

    mindbird.contao.ce.box:
        class: Mindbird\Contao\CEBox\ContentElement\Box
        tags:
            - { name: contao.content_element, category: boxes }

    mindbird.contao.ce.boxHeadlineText:
        class: Mindbird\Contao\CEBox\ContentElement\BoxHeadlineText
        tags:
            - { name: contao.content_element, category: boxes }

    mindbird.contao.ce.boxHeadlineImage:
        class: Mindbird\Contao\CEBox\ContentElement\BoxHeadlineImage
        tags:
            - { name: contao.content_element, category: boxes }

    mindbird.contao.ce.boxStart:
        class: Mindbird\Contao\CEBox\ContentElement\BoxStart
        arguments:
            - '@contao.routing.scope_matcher'
        tags:
            - { name: contao.content_element, category: boxes }

    mindbird.contao.ce.boxEnd:
        class: Mindbird\Contao\CEBox\ContentElement\BoxEnd
        arguments:
            - '@contao.routing.scope_matcher'
        tags:
            - { name: contao.content_element, category: boxes }
