services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    mindbird.contao.ce.box:
        class: Mindbird\Contao\CEBox\ContentElement\Box
        tags:
            - { name: contao.content_element, category: box }

    mindbird.contao.ce.boxHeadlineText:
        class: Mindbird\Contao\CEBox\ContentElement\Box
        tags:
            - { name: contao.content_element, category: box }

    mindbird.contao.ce.boxHeadlineImage:
        class: Mindbird\Contao\CEBox\ContentElement\Box
        tags:
            - { name: contao.content_element, category: box }
